In [60]:
import pandas as pd
import numpy as numpy

df=pd.read_csv("Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv");
df.head(1)

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.0,0.0,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Column Cleaning -> Discarding unwanted column

In [61]:
#Droping unwanted coloumns
df.drop(['id',
'client_id',
'created_by_id',
'last_modified_by_id',
'assigned_to_police_id',
'citizen_accident_id',
'kgid', 
'closed_by_id',
'resolved_by_id',
'gba_identifier',
'veh_no',
'authenticated',
'map_file',    
'route_path',
'meta_data',
'comment',
'reason_breakdown',
'cargo_material',
'age_of_truck',
'veh_type',
'resolved_at_latitude', 'resolved_at_longitude','resolved_at_address','modified_datetime'], axis=1, inplace=True)

df.head(5)

,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,start_datetime,...,direction,description,corridor,priority,created_date,police_station,closed_datetime,resolved_datetime,zone,junction
0,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,2024-03-07 17:01:48.111+00,...,NaN,s m circle in coming man track,Tumkur Road,High,2024-03-07 17:03:51.164032+00,Peenya,NaN,NaN,NaN,NaN
1,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,2024-01-30 04:07:24.173+00,...,NaN,Starting problem,ORR East 1,High,2024-01-30 04:08:22.954979+00,HSR Layout,NaN,2024-01-30 04:17:46.828355+00,NaN,NaN
2,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,2023-11-11 06:18:03.343+00,...,NaN,ಊರ್ವಶಿ ಜಂಕ್ಷನ್ ನಲ್ಲಿ ಒಳಚರಂಡಿ ಚೇಂಬರ್ ಗೆ ಹೊಸದಾಗಿ...,Non-corridor,Low,2023-11-11 06:20:00.989398+00,Wilson Garden,2024-01-30 04:56:03.281509+00,NaN,Central Zone 2,UrvashiJunction
3,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,2024-03-07 17:56:55.061+00,...,NaN,tree fall,Non-corridor,Low,2024-03-07 17:58:56.696892+00,Sadashivanagar,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN
4,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,2024-01-30 04:56:32.348+00,...,NaN,[LOCATION] ಪೈಪ್ [PERSON] ವಾಹನ ಆಫ್ ಆಗಿರುತ್ತದೆ ಸರ್,Non-corridor,Low,2024-01-30 04:58:55.937662+00,Wilson Garden,2024-01-30 05:35:17.338283+00,NaN,NaN,LalbaghMainGateJunc

In [62]:
df.columns = df.columns.str.strip()

ordered_columns = [
    'event_type',
    'event_cause',
    'description',
    'requires_road_closure',
    'status',
    'priority',
    'start_datetime',
    'end_datetime',
    'created_date',
    'closed_datetime',
    'resolved_datetime',
    'latitude',
    'longitude',
    'endlatitude',
    'endlongitude',
    'end_address',
    'address',
    'corridor',
    'junction',
    'zone',
    'direction',
    'police_station'
]

# 3. Reorder the DataFrame
df = df[ordered_columns]

df.head(2)

,event_type,event_cause,description,requires_road_closure,status,priority,start_datetime,end_datetime,created_date,closed_datetime,...,longitude,endlatitude,endlongitude,end_address,address,corridor,junction,zone,direction,police_station
0,unplanned,vehicle_breakdown,s m circle in coming man track,False,closed,High,2024-03-07 17:01:48.111+00,NaN,2024-03-07 17:03:51.164032+00,NaN,...,77.518099,0.0,0.0,NaN,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",Tumkur Road,NaN,NaN,NaN,Peenya
1,unplanned,vehicle_breakdown,Starting problem,False,resolved,High,2024-01-30 04:07:24.173+00,NaN,2024-01-30 04:08:22.954979+00,NaN,...,77.645158,0.0,0.0,NaN,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",ORR East 1,NaN,NaN,NaN,HSR Layout

In [63]:
for col in df.columns:
    print(col)

event_type
event_cause
description
requires_road_closure
status
priority
start_datetime
end_datetime
created_date
closed_datetime
resolved_datetime
latitude
longitude
endlatitude
endlongitude
end_address
address
corridor
junction
zone
direction
police_station

In [64]:
#Writing the cleaned data to a new csv file
df.to_csv("cleaned_astram_event_data.csv", index=False)

Moving Forward

In [94]:
df_master=df.copy()

event_causes = [
    'construction',
    'public_event',
    'procession',
    'vip_movement',
    'protest'
]

df_events = df[
    df['event_cause'].isin(event_causes)
].copy()

print(df_master.shape)
print(df_events.shape)


df_events.head(5)

(8173, 22)
(671, 22)

,event_type,event_cause,description,requires_road_closure,status,priority,start_datetime,end_datetime,created_date,closed_datetime,...,longitude,endlatitude,endlongitude,end_address,address,corridor,junction,zone,direction,police_station
8,planned,public_event,"Cricket Match at M Chinnaswamy Satdium, [LOCAT...",False,closed,High,2024-02-12 02:05:46+00,2024-02-12 14:05:46+00,2024-01-30 05:09:41.077868+00,NaN,...,77.599537,NaN,NaN,NaN,"ಲಿಂಕ್ ರಸ್ತೆ, ಅಶೋಕನಗರ, ಬೆಂಗಳೂರು ಮಧ್ಯ ನಗರ ನಿಗಮ, ...",CBD 2,QueensStatueCircle,NaN,NaN,Cubbon Park
40,planned,construction,[LOCATION] works going on sir,False,closed,High,2024-01-30 11:31:12.848+00,2024-01-30 11:31:46+00,2024-01-30 11:32:15.765069+00,NaN,...,77.698675,0.000000,0.000000,NaN,"Outer Ring Road, Sumadhura Platinum Square, Ka...",ORR East 1,NaN,NaN,NaN,HAL Old Airport
45,planned,construction,NaN,True,closed,Low,2024-01-30 21:21:10.303+00,2024-01-30 21:20:46+00,2024-01-30 21:21:41.722681+00,NaN,...,77.613150,13.008551,77.613128,"Shampura Main Road, AK Colony, Devarajeevana H...","Shampura Main Road, AK Colony, Devarajeevana H...",Non-corridor,NaN,NaN,NaN,K.G. Halli
52,planned,construction,[LOCATION] towards marathhalli and karthiknaga...,False,closed,High,2024-01-30 20:56:01.732+00,2024-01-31 09:05:46+00,2024-01-30 20:56:43.100304+00,NaN,...,77.700635,0.000000,0.000000,NaN,"Outer Ring Road, Karthik Nagar, Marathahalli, ...",ORR East 2,NaN,NaN,NaN,HAL Old Airport
82,planned,construction,karthiknagara towards [LOCATION] and karthikna...,False,closed,High,2024-03-07 21:23:16.629+00,2024-03-08 10:05:46+00,2024-03-07 21:25:40.927133+00,NaN,...,77.700653,0.000000,0.000000,NaN,"Outer Ring Road, Karthik Nagar, Marathahalli, ...",ORR East 2,NaN,NaN,NaN,HAL Old Airport

In [85]:
print(df_master['requires_road_closure'].value_counts(dropna=False))

print(df_master['priority'].value_counts(dropna=False))

print(df_master['status'].value_counts(dropna=False))

requires_road_closure
False    7497
True      676
Name: count, dtype: int64
priority
High    5030
Low     3141
NaN        2
Name: count, dtype: int64
status
closed      7095
active      1007
resolved      71
Name: count, dtype: int64

Priority ->Very usable.

Road Closure ->About 8.3% of incidents require closure.
The classes are imbalanced, but not so extreme that the target is useless.

Status -> Mostly reflects workflow progression (closed/active/resolved).
Not a useful prediction target for your problem.

Next Task : Understand the Event Dataset

In [86]:
print(df_events['requires_road_closure'].value_counts(dropna=False))

print(df_events['priority'].value_counts(dropna=False))

print(df_master['event_cause'].value_counts(dropna=False))

requires_road_closure
False    464
True     207
Name: count, dtype: int64
priority
High    380
Low     291
Name: count, dtype: int64
event_cause
vehicle_breakdown       4896
others                   638
pot_holes                537
construction             480
water_logging            458
accident                 365
tree_fall                284
road_conditions          170
congestion               136
public_event              84
procession                72
vip_movement              20
protest                   15
Debris                    12
test_demo                  3
Fog / Low Visibility       2
debris                     1
Name: count, dtype: int64

In [95]:
df_events['start_datetime'] = pd.to_datetime(df_events['start_datetime'], errors='coerce', format='mixed').dt.tz_localize(None)
df_events['end_datetime'] = pd.to_datetime(df_events['end_datetime'], errors='coerce', format='mixed').dt.tz_localize(None)

# 3. Recalculate your true error count now
actual_start_errors = df_events.loc[df_events['start_datetime'].isna() & df['start_datetime'].notna()]
actual_end_errors = df_events.loc[df_events['end_datetime'].isna() & df['end_datetime'].notna()]

print(f"Actual text formatting errors (Start): {len(actual_start_errors)}")
print(f"Actual text formatting errors (End): {len(actual_end_errors)}")

# 4. Calculate your duration metric safely
df_events['duration_hours'] = (df_events['end_datetime'] - df_events['start_datetime']) / pd.Timedelta(hours=1)

df_events['duration_hours'].describe()

Actual text formatting errors (Start): 0
Actual text formatting errors (End): 0

count      466.000000
mean       278.201606
std       2320.278389
min        -55.499988
25%          0.117620
50%          6.948788
75%         16.999455
max      34184.320343
Name: duration_hours, dtype: float64

In [99]:
# Count negative durations
negative_durations = df_events[df_events['duration_hours'] < 0]
print(f"Number of rows with negative duration: {len(negative_durations)}")

# Display the problematic rows to investigate
negative_durations[['start_datetime', 'end_datetime', 'duration_hours','event_cause']].head()

Number of rows with negative duration: 57

,start_datetime,end_datetime,duration_hours,event_cause
45,2024-01-30 21:21:10.303,2024-01-30 21:20:46.000,-0.006751,construction
158,2024-01-31 22:25:30.936,2024-01-31 18:26:46.000,-3.979149,construction
375,2024-02-03 21:28:38.926,2024-02-03 12:20:46.000,-9.131368,construction
490,2024-02-05 11:23:01.315,2024-02-04 17:25:46.000,-17.954254,construction
1064,2024-02-14 22:05:46.000,2024-02-13 05:22:20.357,-40.723790,public_event

In [100]:
#check the category of negative value grouped with event cause
negative_summary = negative_durations.groupby('event_cause')['duration_hours'].agg(['count', 'min', 'max'])
print(negative_summary)

              count        min        max
event_cause
construction     36 -55.499988  -0.000796
procession        5 -10.999142  -2.952920
public_event      9 -40.723790  -0.001584
vip_movement      7 -42.999963 -24.524401

In [101]:
# Define the thresholds in hours
durations = {
    "24 hours": 24,
    "7 days": 7 * 24,
    "30 days": 30 * 24,
    "365 days": 365 * 24
}

# Calculate and print counts without inspecting rows
for label, hours in durations.items():
    count = (df_events['duration_hours'] > hours).sum()
    print(f"Events longer than {label}: {count}")

Events longer than 24 hours: 102
Events longer than 7 days: 48
Events longer than 30 days: 22
Events longer than 365 days: 3

In [103]:
# Filter for durations greater than 365 days and select specific columns
columns_to_show = ['event_cause', 'start_datetime', 'end_datetime', 'duration_hours', 'status', 'priority']
df_long_events = df_events.loc[df_events['duration_hours'] > (365 * 24), columns_to_show]

# Display the 3 records
df_long_events

,event_cause,start_datetime,end_datetime,duration_hours,status,priority
6647,construction,2023-12-09 00:05:46.000,2026-11-09 11:35:46,25595.500000,active,Low
6648,construction,2023-12-09 00:05:46.000,2026-11-09 11:35:46,25595.500000,active,Low
6894,construction,2023-12-16 03:16:32.764,2027-11-09 11:35:46,34184.320343,active,High

In [104]:
long_events = df_events[df_events['duration_hours'] > 720]
long_events['event_cause'].value_counts()

event_cause
construction    21
public_event     1
Name: count, dtype: int64

In [105]:
df_events.drop(['start_datetime', 'end_datetime', 'duration_hours'], axis=1, inplace=True )

In [106]:
df_events.isnull().sum()

event_type                 0
event_cause                0
description               31
requires_road_closure      0
status                     0
priority                   0
created_date               0
closed_datetime          532
resolved_datetime        671
latitude                   0
longitude                  0
endlatitude               27
endlongitude              27
end_address              465
address                    1
corridor                   0
junction                 505
zone                     348
direction                647
police_station             0
dtype: int64