In [60]:
import pandas as pd
import numpy as numpy

df=pd.read_csv("Astram event data_anonymized - Astram event data_anonymizedb40ac87.csv");
df.head(1)

,id,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,...,resolved_at_address,resolved_at_latitude,resolved_at_longitude,closed_by_id,closed_datetime,resolved_by_id,resolved_datetime,gba_identifier,zone,junction
0,FKID000000,unplanned,13.040004,77.518099,0.0,0.0,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Column Cleaning -> Discarding unwanted column

In [61]:
#Droping unwanted coloumns
df.drop(['id',
'client_id',
'created_by_id',
'last_modified_by_id',
'assigned_to_police_id',
'citizen_accident_id',
'kgid', 
'closed_by_id',
'resolved_by_id',
'gba_identifier',
'veh_no',
'authenticated',
'map_file',    
'route_path',
'meta_data',
'comment',
'reason_breakdown',
'cargo_material',
'age_of_truck',
'veh_type',
'resolved_at_latitude', 'resolved_at_longitude','resolved_at_address','modified_datetime'], axis=1, inplace=True)

df.head(5)

,event_type,latitude,longitude,endlatitude,endlongitude,address,end_address,event_cause,requires_road_closure,start_datetime,...,direction,description,corridor,priority,created_date,police_station,closed_datetime,resolved_datetime,zone,junction
0,unplanned,13.040004,77.518099,0.000000,0.000000,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",NaN,vehicle_breakdown,False,2024-03-07 17:01:48.111+00,...,NaN,s m circle in coming man track,Tumkur Road,High,2024-03-07 17:03:51.164032+00,Peenya,NaN,NaN,NaN,NaN
1,unplanned,12.921876,77.645158,0.000000,0.000000,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",NaN,vehicle_breakdown,False,2024-01-30 04:07:24.173+00,...,NaN,Starting problem,ORR East 1,High,2024-01-30 04:08:22.954979+00,HSR Layout,NaN,2024-01-30 04:17:46.828355+00,NaN,NaN
2,unplanned,12.955622,77.585708,0.000000,0.000000,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",NaN,others,False,2023-11-11 06:18:03.343+00,...,NaN,ಊರ್ವಶಿ ಜಂಕ್ಷನ್ ನಲ್ಲಿ ಒಳಚರಂಡಿ ಚೇಂಬರ್ ಗೆ ಹೊಸದಾಗಿ...,Non-corridor,Low,2023-11-11 06:20:00.989398+00,Wilson Garden,2024-01-30 04:56:03.281509+00,NaN,Central Zone 2,UrvashiJunction
3,unplanned,13.006147,77.579435,13.006239,77.579516,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...","Sankey Road, Palace Orchard Upper, Sadashiva N...",tree_fall,True,2024-03-07 17:56:55.061+00,...,NaN,tree fall,Non-corridor,Low,2024-03-07 17:58:56.696892+00,Sadashivanagar,2024-03-14 07:42:05.54944+00,NaN,NaN,NaN
4,unplanned,12.953980,77.585233,0.000000,0.000000,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",NaN,vehicle_breakdown,False,2024-01-30 04:56:32.348+00,...,NaN,[LOCATION] ಪೈಪ್ [PERSON] ವಾಹನ ಆಫ್ ಆಗಿರುತ್ತದೆ ಸರ್,Non-corridor,Low,2024-01-30 04:58:55.937662+00,Wilson Garden,2024-01-30 05:35:17.338283+00,NaN,NaN,LalbaghMainGateJunc

In [62]:
df.columns = df.columns.str.strip()

ordered_columns = [
    'event_type',
    'event_cause',
    'description',
    'requires_road_closure',
    'status',
    'priority',
    'start_datetime',
    'end_datetime',
    'created_date',
    'closed_datetime',
    'resolved_datetime',
    'latitude',
    'longitude',
    'endlatitude',
    'endlongitude',
    'end_address',
    'address',
    'corridor',
    'junction',
    'zone',
    'direction',
    'police_station'
]

# 3. Reorder the DataFrame
df = df[ordered_columns]

df.head(2)

,event_type,event_cause,description,requires_road_closure,status,priority,start_datetime,end_datetime,created_date,closed_datetime,...,longitude,endlatitude,endlongitude,end_address,address,corridor,junction,zone,direction,police_station
0,unplanned,vehicle_breakdown,s m circle in coming man track,False,closed,High,2024-03-07 17:01:48.111+00,NaN,2024-03-07 17:03:51.164032+00,NaN,...,77.518099,0.0,0.0,NaN,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",Tumkur Road,NaN,NaN,NaN,Peenya
1,unplanned,vehicle_breakdown,Starting problem,False,resolved,High,2024-01-30 04:07:24.173+00,NaN,2024-01-30 04:08:22.954979+00,NaN,...,77.645158,0.0,0.0,NaN,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",ORR East 1,NaN,NaN,NaN,HSR Layout

In [63]:
for col in df.columns:
    print(col)

event_type
event_cause
description
requires_road_closure
status
priority
start_datetime
end_datetime
created_date
closed_datetime
resolved_datetime
latitude
longitude
endlatitude
endlongitude
end_address
address
corridor
junction
zone
direction
police_station

In [64]:
#Writing the cleaned data to a new csv file
df.to_csv("cleaned_astram_event_data.csv", index=False)